# Generated by Django 4.0.5 on 2022-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0002_rename_text_topic_name_discuss_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='text',
        ),
    ]
