# Generated by Django 4.0.5 on 2022-06-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0003_rename_date_time_discuss_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=20000)),
            ],
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='discuss',
            name='head',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
