# Generated by Django 4.0.5 on 2022-06-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0004_message_rename_date_time_topic_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='discuss',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forum_body.discuss'),
            preserve_default=False,
        ),
    ]
