# Generated by Django 4.0.5 on 2022-06-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0006_rename_message_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='discuss',
        ),
    ]
