# Generated by Django 4.0.5 on 2022-06-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0007_remove_messages_discuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='discus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum_body.discuss'),
            preserve_default=False,
        ),
    ]
