# Generated by Django 4.0.5 on 2022-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0008_messages_discus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='discus',
            new_name='discuss',
        ),
    ]
