# Generated by Django 4.0.5 on 2022-06-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0009_rename_discus_messages_discuss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='discuss',
        ),
    ]
