# Generated by Django 4.0.5 on 2022-07-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_body', '0012_messages_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='nickname',
        ),
    ]
